### ISSUE TITLE
500 Internal Server Error while processing a LC jpeg file.

### ISSUE THREAD

**Issue by cchou** [fcla/pim#2]
while processing http://lcweb2.loc.gov/natlib/ihas/service/gottlieb/09601/ver01/0001v.jpg, pim return an internal server error.

128.227.228.235 - - [05/Jun/2013 13:58:50] "GET /favicon.ico HTTP/1.1" 404 18 0.0013
Net::HTTPFatalError - 500 "Internal Server Error":
    /usr/lib/ruby/1.8/net/http.rb:2105:in `error!'
    ./app.rb:205:in`GET /describe/results'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1211:in `call'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1211:in`compile!'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in `[]'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in`route!'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:788:in `route_eval'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in`route!'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:821:in `process_route'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:819:in`catch'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:819:in `process_route'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:771:in`route!'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:770:in `each'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:770:in`route!'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:886:in `dispatch!'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:706:in`call!'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in `invoke'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in`catch'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in `invoke'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:706:in`call!'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:692:in `call'
    /var/www/description/pim/bundle/ruby/1.8/gems/rack-protection-1.1.4/lib/rack/protection/xss_header.rb:22:in`call'
    /var/www/description/pim/bundle/ruby/1.8/gems/rack-protection-1.1.4/lib/rack/protection/path_traversal.rb:16:in `call'
    /var/www/description/pim/bundle/ruby/1.8/gems/rack-protection-1.1.4/lib/rack/protection/json_csrf.rb:17:in`call'
    /var/www/description/pim/bundle/ruby/1.8/gems/rack-protection-1.1.4/lib/rack/protection/base.rb:47:in `call'
    /var/www/description/pim/bundle/ruby/1.8/gems/rack-protection-1.1.4/lib/rack/protection/xss_header.rb:22:in`call'
    /var/www/description/pim/bundle/ruby/1.8/gems/rack-1.3.5/lib/rack/logger.rb:15:in `call'
    /var/www/description/pim/bundle/ruby/1.8/gems/rack-1.3.5/lib/rack/commonlogger.rb:20:in`call'
    /var/www/description/pim/bundle/ruby/1.8/gems/rack-1.3.5/lib/rack/head.rb:9:in `call'
    /var/www/description/pim/bundle/ruby/1.8/gems/rack-1.3.5/lib/rack/methodoverride.rb:24:in`call'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334:in `call'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1403:in`synchronize'
    /var/www/description/pim/bundle/ruby/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334:in `call'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/connection.rb:84:in`pre_process'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/connection.rb:82:in `catch'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/connection.rb:82:in`pre_process'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/connection.rb:57:in `process'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/connection.rb:42:in`receive_data'
    /var/www/description/pim/bundle/ruby/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    /var/www/description/pim/bundle/ruby/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/backends/base.rb:61:in `start'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/server.rb:159:in`start'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/controllers/controller.rb:86:in `start'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/runner.rb:185:in`send'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/runner.rb:185:in `run_command'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/runner.rb:151:in`run!'
    /var/www/description/pim/bundle/ruby/1.8/gems/thin-1.2.11/bin/thin:6
    /local/mongrel/.gem/ruby/1.8/gems/bin/thin:19:in `load'
    /local/mongrel/.gem/ruby/1.8/gems/bin/thin:19
128.227.228.235 - - [05/Jun/2013 13:58:58] "GET /describe/results?document=http%3A%2F%2Flcweb2.loc.gov%2Fnatlib%2Fihas%2Fservice%2Fgottlieb%2F09601%2Fver01%2F0001v.jpg&id_type=uri&id_value=1&ieid_type=&ieid_value= HTTP/1.1" 500 30 2.4373

**Comment by cchou** [comment]
Fix has been deployed to pim.fcla.edu.
